### ISSUE TITLE
Do woc collect repositories in launchpad.net?

### ISSUE THREAD

**Issue by gaokai320** [ssc-oscar/gather#12]
I'm doing some explorations on ubuntu packages. And I find that ubuntu hosts its packages in https://launchpad.net/, which is a software collaboration platform like GitHub. I have two questions:
1. do woc collect repositories in launchpad?
2. what platforms do woc collect repositories from? 

I go through this repository and find that [run2210.sh](https://github.com/ssc-oscar/gather/blob/a08757482b230cdff51df1e793360518de9311b4/run2210.sh) seems to be woc's repository collection script. From it, I find many platforms but didn't find launchpad

**Comment by audrism** [comment]
1. see run2303.sh for the latest list
2. Projects from launchpad are in WoC, not sure when they stopped being updated. I suspect launchpad made it difficult to gather data. Do you have a list?

**Comment by gaokai320** [comment]
Listing repositories in launchpad is not straightforward. I first crawl all projects registered in launchpad, the crawl all git repositories of each project. I have written a python script and am running it. If finished successfully, I will open a PR.

**Comment by audrism** [comment]
Many thanks!

**Comment by gaokai320** [comment]
See #13 for the PR.
The collection process takes about 16 hours. Although there are 45,084 projects registered in launchpad. Only 3,439 projects have git repositories. Among them: 
- [ubuntu](https://code.launchpad.net/ubuntu) projects have 48139 git repositories.
- the remaining 3,438 projects have 9293 git repositories.

Only we only collect repositories under [ubuntu](https://code.launchpad.net/ubuntu) projects, the collection process will only take few minutes.
