### ISSUE TITLE
GL dropped last page from the headers: need to iterate over next

### ISSUE THREAD

**Issue by audrism** [ssc-oscar/gather#4]
@zol0 should not be difficult to fix. The loop needs to be while. If killed, need to output the last page served.

**Comment by zol0** [comment]
updated glRepos.py to iterate using 'rel=next' header from link. a failed page load does not exit the script immediately, script now only exits after 5 successive failed pages (likely indicating last page has been reached)

**Comment by audrism** [comment]
worked!
