### ISSUE TITLE
Drupal trouble

### ISSUE THREAD

**Issue by noah-22** [ssc-oscar/gather#9]
Hi @audrism,

@dlomax64  and I are having trouble getting Drupal and Debian to work, both for differing reasons.

### Drupal
We both get SSH key errors:
```shell
$ git ls-remote dr:drupal
git@git.drupal.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
_Update: Debian works. It did not before_

**Comment by noah-22** [comment]
P.S. all other `git ls-remote` commands are working!

**Comment by audrism** [comment]
Looks like drupal may have changed their git urls:

git ls-remote dr:project/drupal.git

**Comment by audrism** [comment]
https://www.drupal.org/project/drupal/git-instructions

**Comment by audrism** [comment]
Yes, looks like key does not work for deb: 

git ls-remote deb:webmaster-team/webwml
Permission denied (publickey).
fatal: Could not read from remote repository.

The https, does work, however:

[audris@acf-login5 ght.24]$ git ls-remote https://salsa.debian.org/webmaster-team/webwml

**Comment by sylviesworld** [comment]
Both work through ssh for me now. @noah-22 for drupal I had to accept their terms & conditions before it would let me. Try logging on again and see if it prompts you to do so.

**Comment by noah-22** [comment]
> Both work through ssh for me now. @noah-22 for drupal I had to accept their terms & conditions before it would let me. Try logging on again and see if it prompts you to do so.

Yes, going to [drupal.org](drupal.org) -> My account -> Profile -> Git access and accepting terms then setting a git username let me SSH. Thanks.
